
const nodemailer = require('nodemailer');


const sendPasswordEmail = async (customerEmail, password) => {

  let transporter = nodemailer.createTransport({
    host: "teja.doodleblue@gmail.com",
    port: 465,
    secure: true,
    service: 'gmail',
    auth: {
      user: 'teja.doodleblue@gmail.com',
      pass: 'dfnu rgte kjja aclk'
    }
  });

  const mailOptions = {
    from: 'teja.doodleblue@gmail.com',
    to: customerEmail,
    subject: 'Your autogenerated password',
    text: `Hello,\n\nYour autogenerated password is: ${password}\n\nPlease keep this password secure.\n\nThank you!\n\nTeja.`
  };

  try {

    await transporter.sendMail(mailOptions);
    console.log(`Email sent to ${customerEmail} with autogenerated password.`);
  } catch (error) {
    console.error('Error sending email:', error);
    throw error;
  }
};
const sendEmailNotification = async (params) => {
  const mailOptions = {
    from: 'teja.doodleblue@gmail.com',
    to:params.email ,
    subject: params.subject,
    text: params.text
  };
  let transporter = nodemailer.createTransport({
    host: "teja.doodleblue@gmail.com",
    port: 465,
    secure: true,
    service: 'gmail',
    auth: {
      user: 'teja.doodleblue@gmail.com',
      pass: 'dfnu rgte kjja aclk'
    }
  });

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.error('Error sending email:', error);
    } else {
      console.log('Email sent:', info.response);
    }
  });
}

module.exports = {
  sendEmailNotification, sendPasswordEmail
}


